# Generated by Django 5.2.13 on 2026-04-14 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FunctionDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function_id', models.CharField(max_length=120, unique=True)),
                ('label', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('runner_path', models.CharField(max_length=255)),
                ('param_schema', models.JSONField(default=dict)),
                ('output_type', models.CharField(default='table', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='FunctionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExecutionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('params', models.JSONField(default=dict)),
                ('status', models.CharField(default='success', max_length=30)),
                ('result_payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('function', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='dashboard.functiondefinition')),
            ],
        ),
        migrations.CreateModel(
            name='ExecutionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('params', models.JSONField(default=dict)),
                ('status', models.CharField(default='success', max_length=30)),
                ('result_preview', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('function', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='dashboard.functiondefinition')),
            ],
        ),
        migrations.AddField(
            model_name='functiondefinition',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='functions', to='dashboard.functiongroup'),
        ),
        migrations.CreateModel(
            name='UserPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('params', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('function', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presets', to='dashboard.functiondefinition')),
            ],
        ),
    ]
