# Generated by Django 6.0.1 on 2026-04-27 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=10, unique=True)),
                ('company_name', models.CharField(blank=True, default='', max_length=200)),
                ('price', models.FloatField(default=0)),
                ('change_percent', models.FloatField(default=0)),
                ('volume', models.BigIntegerField(default=0)),
                ('avg_volume_value', models.FloatField(default=0)),
                ('rsi', models.FloatField(default=50)),
                ('adx', models.FloatField(default=25)),
                ('plus_di', models.FloatField(default=0)),
                ('minus_di', models.FloatField(default=0)),
                ('cmf', models.FloatField(default=0)),
                ('atr', models.FloatField(default=0)),
                ('sma_10', models.FloatField(default=0)),
                ('sma_20', models.FloatField(default=0)),
                ('sma_50', models.FloatField(default=0)),
                ('bb_upper', models.FloatField(default=0)),
                ('bb_middle', models.FloatField(default=0)),
                ('bb_lower', models.FloatField(default=0)),
                ('bb_percent', models.FloatField(default=50)),
                ('macd', models.FloatField(default=0)),
                ('macd_signal', models.FloatField(default=0)),
                ('volume_ratio', models.FloatField(default=1.0)),
                ('pe', models.FloatField(blank=True, null=True)),
                ('pb', models.FloatField(blank=True, null=True)),
                ('roe', models.FloatField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'stock_data',
                'ordering': ['-avg_volume_value'],
            },
        ),
        migrations.CreateModel(
            name='SyncStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('idle', 'Idle'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='idle', max_length=20)),
                ('total_symbols', models.IntegerField(default=0)),
                ('processed_symbols', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sync_status',
            },
        ),
        migrations.CreateModel(
            name='StockAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master_score', models.IntegerField(default=50)),
                ('technical_score', models.IntegerField(default=50)),
                ('fundamental_score', models.IntegerField(default=50)),
                ('signal', models.CharField(default='WAIT', max_length=20)),
                ('entry_price', models.FloatField(default=0)),
                ('stop_loss', models.FloatField(default=0)),
                ('take_profit', models.FloatField(default=0)),
                ('risk_reward_ratio', models.FloatField(default=0)),
                ('is_vetoed', models.BooleanField(default=False)),
                ('veto_reason', models.CharField(blank=True, default='', max_length=200)),
                ('is_fast_pick', models.BooleanField(default=False)),
                ('is_short_term_qualified', models.BooleanField(default=False)),
                ('is_slow_mode', models.BooleanField(default=False)),
                ('is_high_risk', models.BooleanField(default=False)),
                ('has_inverted_sl', models.BooleanField(default=False)),
                ('estimated_days_to_target', models.FloatField(default=0)),
                ('criteria_met', models.IntegerField(default=0)),
                ('criteria_list', models.JSONField(default=list)),
                ('trend', models.CharField(default='SIDEWAYS', max_length=20)),
                ('breakout_status', models.CharField(default='', max_length=50)),
                ('market_rsi', models.FloatField(default=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('symbol', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='dashboard.stockdata')),
            ],
            options={
                'db_table': 'stock_analysis',
                'ordering': ['-risk_reward_ratio', '-master_score'],
            },
        ),
    ]
