# Generated by Django 6.0.1 on 2026-04-28 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_add_stock_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockdata',
            name='f_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stockdata',
            name='ichimoku_kijun',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='stockdata',
            name='ichimoku_status',
            field=models.CharField(default='neutral', max_length=20),
        ),
        migrations.AddField(
            model_name='stockdata',
            name='ichimoku_tenkan',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='stockdata',
            name='mfi',
            field=models.FloatField(default=50),
        ),
        migrations.AddField(
            model_name='stockdata',
            name='supertrend',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='stockdata',
            name='supertrend_signal',
            field=models.CharField(default='neutral', max_length=20),
        ),
        migrations.AddField(
            model_name='stockdata',
            name='vwap',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='stockdata',
            name='vwap_status',
            field=models.CharField(default='neutral', max_length=20),
        ),
    ]
