# Generated by Django 6.0.1 on 2026-04-28 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_add_advanced_indicators'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockdata',
            name='industry',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='stockdata',
            name='market_group',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
