# Generated by Django 6.0.1 on 2026-04-28 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_add_industry_market_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockanalysis',
            name='expected_profit_per_day',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='stockanalysis',
            name='timeframe_color',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='stockanalysis',
            name='timeframe_label',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='stockanalysis',
            name='upside_per_day',
            field=models.FloatField(default=0),
        ),
    ]
