# Generated by Django 6.0.1 on 2026-04-28 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_separated_risk'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockanalysis',
            name='target_yield_pct',
            field=models.FloatField(default=0),
        ),
    ]
