# Generated by Django 6.0.1 on 2026-04-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_add_target_yield_pct'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockanalysis',
            name='base_master_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stockanalysis',
            name='market_weight',
            field=models.IntegerField(default=0),
        ),
    ]
