# Generated by Django 6.0.1 on 2026-04-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_add_score_breakdown'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockanalysis',
            name='stock_risk_reason',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='stockanalysis',
            name='base_master_score',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='stockanalysis',
            name='market_weight',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stockanalysis',
            name='is_safe_entry',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stockanalysis',
            name='has_high_resistance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stockanalysis',
            name='avg_volume_value',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='stockanalysis',
            name='trend_factor',
            field=models.FloatField(default=0.6),
        ),
    ]
