# Generated by Django 6.0.1 on 2026-04-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_add_safe_entry_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockanalysis',
            name='foreign_buy_streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stockanalysis',
            name='foreign_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stockanalysis',
            name='industry_performance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='stockanalysis',
            name='is_industry_leader',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='stockanalysis',
            name='hard_risk_pct',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='stockanalysis',
            name='support_price',
            field=models.FloatField(default=0),
        ),
    ]
