# Generated by Django 6.0.1 on 2026-04-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_add_smart_money_industry'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockanalysis',
            name='pe_industry_avg',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='stockanalysis',
            name='early_exit_trigger_pct',
            field=models.FloatField(default=2.0),
        ),
        migrations.AddField(
            model_name='stockanalysis',
            name='early_exit_drop_pct',
            field=models.FloatField(default=0.7),
        ),
        migrations.AddField(
            model_name='stockanalysis',
            name='optimal_position_size',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='stockanalysis',
            name='account_balance',
            field=models.FloatField(default=100000000),
        ),
        migrations.AddField(
            model_name='stockanalysis',
            name='risk_tolerance_pct',
            field=models.FloatField(default=2.0),
        ),
    ]
