# Generated by Django 6.0.1 on 2026-05-01 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_add_early_exit_money_mgmt'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuarterlyFinancial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=10)),
                ('quarter', models.CharField(max_length=10)),
                ('quarter_date', models.DateField()),
                ('roe', models.FloatField(blank=True, null=True)),
                ('roa', models.FloatField(blank=True, null=True)),
                ('pe', models.FloatField(blank=True, null=True)),
                ('pb', models.FloatField(blank=True, null=True)),
                ('f_score_roc', models.IntegerField(default=0)),
                ('f_score_roa', models.IntegerField(default=0)),
                ('f_score_accrual', models.IntegerField(default=0)),
                ('f_score', models.IntegerField(default=0)),
                ('revenue', models.BigIntegerField(blank=True, null=True)),
                ('net_profit', models.BigIntegerField(blank=True, null=True)),
                ('profit_growth', models.FloatField(blank=True, null=True)),
                ('is_vetoed', models.BooleanField(default=False)),
                ('veto_reason', models.CharField(blank=True, default='', max_length=200)),
                ('vci_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'quarterly_financial',
                'ordering': ['-quarter_date'],
                'unique_together': {('symbol', 'quarter')},
            },
        ),
    ]
