# Generated by Django 5.x on 2026-07-09
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0027_stockanalysis_scan_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockanalysis",
            name="entry_quality",
            field=models.CharField(default="GOOD", max_length=20),
        ),
        migrations.AddField(
            model_name="stockanalysis",
            name="entry_quality_reason",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
