# Generated by Django 6.0.1 on 2026-07-09 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_add_entry_quality_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockanalysis',
            name='scan_mode',
            field=models.CharField(default='EARLY_TREND', max_length=20),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='sector_group',
            field=models.CharField(blank=True, default='', help_text='Nhóm ngành rộng: cyclical/banking/growth_defensive/general', max_length=50),
        ),
    ]
