# Generated by Django 6.0.5 on 2026-07-09 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_alter_stockanalysis_scan_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockanalysis',
            name='foreign_absorption_ratio',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='stockanalysis',
            name='latest_net_val',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='stockanalysis',
            name='latest_net_val_2',
            field=models.FloatField(default=0.0),
        ),
    ]
