# Generated by Django 6.0.5 on 2026-07-09 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_stockanalysis_foreign_absorption_ratio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockanalysis',
            name='foreign_master_modifier',
            field=models.IntegerField(default=0),
        ),
    ]
