# Generated by Django Cursor Agent on 2026-07-10
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_stockanalysis_foreign_master_modifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockanalysis',
            name='foreign_buy_val',
            field=models.FloatField(default=0.0, help_text='Giá trị mua khối ngoại phiên gần nhất (VND)'),
        ),
        migrations.AddField(
            model_name='stockanalysis',
            name='foreign_sell_val',
            field=models.FloatField(default=0.0, help_text='Giá trị bán khối ngoại phiên gần nhất (VND)'),
        ),
        migrations.AddField(
            model_name='stockanalysis',
            name='foreign_trading_share',
            field=models.FloatField(default=0.0, help_text='Tỷ lệ giao dịch khối ngoại/tổng thanh khoản phiên (%)'),
        ),
        migrations.AddField(
            model_name='stockanalysis',
            name='foreign_accumulated_trend',
            field=models.CharField(default='NEUTRAL', help_text='Xu hướng lũy kế 30 phiên: ACCUMULATING/DISTRIBUTING/NEUTRAL', max_length=20),
        ),
        migrations.AddField(
            model_name='stockanalysis',
            name='foreign_accumulated_slope',
            field=models.FloatField(default=0.0, help_text='Độ dốc đường lũy kế net_val 30 phiên'),
        ),
    ]
